name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and Corepack
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install dependencies with Yarn
        run: |
          corepack enable
          yarn install
        working-directory: ./desktop-app

      - name: Run tests and linting
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package
          yarn lint
          yarn exec tsc
          yarn test
        working-directory: ./desktop-app
